from typing import Any

class CircularBufferABC:
    def __init__(self, maxlen: int) -> None: ...
    @property
    def maxlen(self) -> int: ...
    def enqueue(self, x: Any, /) -> None: ...
    def dequeue(self) -> Any: ...
    def __len__(self) -> int: ...

class CircularBuffer_c(CircularBufferABC): ...
class CircularLinkedListDynamic_c(CircularBufferABC): ...
class CircularLinkedListStatic_c(CircularBufferABC): ...
